name: Run Playwright Tests and Report to Qase

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar Playwright
        run: npx playwright install --with-deps

      - name: Executar testes Playwright e enviar resultados ao Qase
        run: |
          export QASE_API_TOKEN="${{ secrets.QASE_API_TOKEN }}"
          npx playwright test tests/registrar.spec.js
